title: Carl Patten MBCS
description: Synapex — Business Analysis & Data Analytics

url: "https://synapex.co.uk"
baseurl: ""

lang: en-GB

author:
  name: Carl Patten
  url: "https://synapex.co.uk"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

